# Use OpenJDK 17 as the base image for the Spring Boot backend
FROM openjdk:17-jdk-slim AS backend

WORKDIR /app

# Copy the JAR file of the Spring Boot application
COPY target/springboot-backend-0.0.1-SNAPSHOT.jar app.jar

# Expose the port for the backend service
EXPOSE 8080

# Run the Spring Boot application
CMD ["java", "-jar", "app.jar"]

